### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DisruptionSystemsINC** [Resourceful-Bees/ResourcefulBees#376]
### Bug Description

ALL Bees stop entering beehives when an incomplete apiary is nearby

### How to Reproduce?

1. Build a beehive
2. Place an apiary without completing the structure
3. The bees will stop entering the beehive at night/when they have pollen

### Expected Behavior

The bees will continue to enter the beehive as usual

### Version

0.10.7

### Mod Loader Version

1.16.5 - 36.2.39

### Acknowledgement

- [X] I agree that I read the terms at the top of the page.

**Comment by Epic428** [comment]
Really you shouldn’t be placing apiaries with unfinished structures. They won’t do anything anyway so there’s zero point to doing so. I don’t recall ever seeing the phenomenon in all the testing I’d done. But also support for the 1.16.5 version is essentially non-existent at this point due to our focus on updating 1.19.2 to 1.20
